---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Max
--- DateTime: 10/07/2022 21:23
---

---@return number
---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@param bonus number @The bonus to apply to final score before deciding max skill level. Can be left nil.
local function getMaxSkill(character, perk, bonus)
    local character_traits = character:getTraits()
    local character_profession_str = character:getDescriptor():getProfession()
    local trait_perk_level = 0

    -- Go through all traits and add their relevant perk level to the total
    for i=0, character_traits:size()-1 do
        local trait_str = character_traits:get(i);
        local trait = TraitFactory.getTrait(trait_str)
        local map = trait:getXPBoostMap();
        if map then
            local mapTable = transformIntoKahluaTable(map)
            for trait_perk, level in pairs(mapTable) do
                if trait_perk:getName() == perk:getName() then
                    trait_perk_level = trait_perk_level + level:intValue()
                end
            end
        end
    end

    local character_profession = ProfessionFactory.getProfession(character_profession_str)

    -- Go through the XPBoostMap of the profession and add the relevant perk level to the total
    local profession_xp_boost_map = character_profession:getXPBoostMap()
    if profession_xp_boost_map then
        local mapTable = transformIntoKahluaTable(profession_xp_boost_map)
        for prof_perk, level in pairs(mapTable) do
            if prof_perk:getName() == perk:getName() then
                trait_perk_level = trait_perk_level + level:intValue()
            end
        end
    end

    if bonus then
        trait_perk_level = trait_perk_level + bonus
    end

    print("SkillLimiter: Trait Perk Level: " .. trait_perk_level)

    if trait_perk_level == 0 then
        return 5
    end
    if trait_perk_level == 1 then
        return 7
    end
    if trait_perk_level == 2 then
        return 9
    end
    if trait_perk_level >= 3 then
        return 10
    end
end

---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@param level Integer
---@param levelUp Boolean
local function limitSkill(character, perk, level, levelUp)
    -- If not levelUp, then we do not need to check whether or not we should cap the skill.
    -- This also prevents infinite loops, since this function can cause a LevelPerk event to be fired.
    if not levelUp then
        return
    end

    -- If perk is Strength, Fitness, or Piano, return.
    -- These are physical skills, and we do not need to limit them.
    local perk_name = perk:getName():lower()
    if perk_name == "strength" or perk_name == "fitness" or perk_name == "piano" then
        return
    end

    local bonus = 0

    -- If perk is Sprinting, Lightfooted, Nimble, or Sneaking, then we give a +2 bonus.
    if perk_name == "sprinting" or perk_name == "lightfooted" or perk_name == "nimble" or perk_name == "sneaking" then
        bonus = 2
    end

    -- If perk is Axe, Long Blunt, Short Blunt, Long Blade, Short Blade, Spear, Maintenance, Aiming, or Reloading, then we give a +1 bonus.
    if perk_name == "axe" or perk_name == "long blunt" or perk_name == "short blunt" or perk_name == "long blade" or perk_name == "short blade" or perk_name == "spear" or perk_name == "maintenance" or perk_name == "aiming" or perk_name == "reloading" then
        bonus = 1
    end

    -- Get the maximum skill level for this perk, based on the character's traits & profession.
    local max_skill = getMaxSkill(character, perk, bonus)
    if max_skill == nil then
        return
    end

    if level > max_skill then
        -- Cap the skill level.
        character:setPerkLevelDebug(perk, max_skill)
    end

    print("SkillLimiter: " .. character:getFullName() .. " leveled up " .. perk:getName() .. " and was capped to " .. max_skill .. ".")
end

Events.LevelPerk.Add(limitSkill)